function escolha() {
    let input = document.getElementById('input').value
    let res = document.getElementById('res')

    res.innerHTML = `Sua escolha foi : ${input}`
}

window.addEventListener('load', ()=> {
    let comidas = [
        'Abacate',
        'Abóbora',
        'Abobrinha',
        'Açaí',
        'Acarajé',
        'Acelga',
        'Aipim',
        'Alcaparra',
        'Alecrim',
        'Alface',
        'Alho',
        'Alho-poró',
        'Amêndoa',
        'Amendoim',
        'Amendoim torrado',
        'Ananás',
        'Anchova',
        'Arroz',
        'Arroz integral',
        'Aspargo',
        'Atum',
        'Azeitona',
        'Bacalhau',
        'Baião de dois',
        'Bife',
        'Biscoito',
        'Bolacha',
        'Bolinho de chuva',
        'Bolinho de carne',
        'Borrego',
        'Brigadeiro',
        'Broto de feijão',
        'Bruschetta',
        'Cabelinho de milho',
        'Cachaça',
        'Cacau',
        'Cacho de uva',
        'Cale',
        'Camarão',
        'Canelone',
        'Capuccino',
        'Caranguejo',
        'Carne de sol',
        'Carne moída',
        'Castanha-do-pará',
        'Cebola',
        'Cebolinha',
        'Ceviche',
        'Chia',
        'Chips de batata',
        'Chocolate',
        'Chocolate amargo',
        'Chocolate branco',
        'Chocolate ao leite',
        'Churros',
        'Cloro',
        'Coco',
        'Coentro',
        'Confit',
        'Costela',
        'Couve',
        'Couve-flor',
        'Crouton',
        'Cuscuz',
        'Daspa',
        'Donut',
        'Dorito',
        'Enchilada',
        'Espaguete',
        'Esfiha',
        'Falafel',
        'Feijão',
        'Feijão preto',
        'Fettuccine',
        'Filé',
        'Frango',
        'Frango assado',
        'Frango grelhado',
        'Fruta',
        'Fritada',
        'Fritas',
        'Fritura',
        'Funghi',
        'Galinha',
        'Gengibre',
        'Grão-de-bico',
        'Guacamole',
        'Haddock',
        'Hamburguer',
        'Haricot',
        'Hummus',
        'Jaca',
        'Jambalaya',
        'Japadog',
        'Jiló',
        'Kibe',
        'Lasanha',
        'Lentilha',
        'Limão',
        'Lombo',
        'Macarrão',
        'Macarrão integral',
        'Maçã',
        'Manteiga',
        'Maracujá',
        'Marisco',
        'Marmita',
        'Mousse',
        'Nhoque',
        'Ostra',
        'Panqueca',
        'Papaya',
        'Pão',
        'Pão de queijo',
        'Pão integral',
        'Parmesão',
        'Peixe',
        'Percevejo',
        'Pêssego',
        'Pizza',
        'Polenta',
        'Pão de forma',
        'Pudim',
        'Purê',
        'Queijo',
        'Quiche',
        'Rabanete',
        'Radicchio',
        'Ramen',
        'Ravioli',
        'Refogado',
        'Risoto',
        'Salada',
        'Salame',
        'Salmão',
        'Sardinha',
        'Salsicha',
        'Salsão',
        'Sanduíche',
        'Sopa',
        'Sorvete',
        'Suco',
        'Sushi',
        'Tacacá',
        'Tapioca',
        'Tofu',
        'Tomate',
        'Torta',
        'Trufa',
        'Uva',
        'Vale',
        'Yakissoba',
        'Yoghurt',
        'Zucchini',
        'Abóbora japonesa',
        'Abóbora italiana',
        'Acelga chinesa',
        'Adocicado',
        'Agrião',
        'Alcachofra',
        'Almeirão',
        'Amêndoas',
        'Anis',
        'Arroz de coco',
        'Arroz doce',
        'Azeitona preta',
        'Azeitona verde',
        'Baked beans',
        'Bacalhau à brás',
        'Bacon',
        'Baloné',
        'Barata',
        'Batata-doce',
        'Berinjela',
        'Big Mac',
        'Biscoito de polvilho',
        'Bolacha de água e sal',
        'Bolinho de bacalhau',
        'Bolo',
        'Bolo de cenoura',
        'Bolo de chocolate',
        'Bolo de milho',
        'Bolo de laranja',
        'Bolo de maçã',
        'Bolo de nozes',
        'Bolo inglês',
        'Brócolis',
        'Caldo verde',
        'Canja de galinha',
        'Caneloni',
        'Capuccino gelado',
        'Caramelo',
        'Carne assada',
        'Carne de porco',
        'Carne de cordeiro',
        'Carne grelhada',
        'Caruru',
        'Castanha de caju',
        'Cevada',
        'Chuchu',
        'Coentro',
        'Costelinha',
        'Coxinha',
        'Creme de leite',
        'Creme brûlée',
        'Croissant',
        'Croquete',
        'Cuscuz paulista',
        'Doce de leite',
        'Doce de abóbora',
        'Doce de leite condensado',
        'Doce de figo',
        'Doce de pêssego',
        'Frango à passarinho',
        'Frango ao molho',
        'Fruta cristalizada',
        'Fruta seca',
        'Galinha à cabidela',
        'Gelatina',
        'Gorgonzola',
        'Grão-de-bico assado',
        'Guaraná',
        'Hortelã',
        'Iogurte grego',
        'Jujuba',
        'Ketchup',
        'Kibe assado',
        'Kibe cru',
        'Lasanha de berinjela',
        'Linguiça',
        'Manteiga de amendoim',
        'Manteiga de leite',
        'Manteiga de coco',
        'Marmelo',
        'Mel',
        'Melancia',
        'Melão',
        'Meringue',
        'Milho verde',
        'Mistura',
        'Molho barbecue',
        'Molho de tomate',
        'Molho pesto',
        'Muffin',
        'Mung bean',
        'Nhoque de batata',
        'Nutella',
        'Orelha de pau',
        'Ovelha',
        'Paella',
        'Panetone',
        'Pão sírio',
        'Pão de ló',
        'Pão de mel',
        'Peito de frango',
        'Picanha',
        'Pipoca',
        'Pizza de calabresa',
        'Pizza de marguerita',
        'Pizza de quatro queijos',
        'Piquenique',
        'Polvo',
        'Pudim de leite',
        'Quindim',
        'Rapadura',
        'Requeijão',
        'Rúcula',
        'Salada de frutas',
        'Salame defumado',
        'Salmão defumado',
        'Sanduíche de frango',
        'Sanduíche de presunto',
        'Sardinha em conserva',
        'Sopa de cebola',
        'Sorvete de chocolate',
        'Sorvete de morango',
        'Sushi de salmão',
        'Sushi de atum',
        'Taco',
        'Tapioca doce',
        'Taco de carne',
        'Tiramisu',
        'Tomate seco',
        'Trança de chocolate',
        'Tutu de feijão',
        'Uva passa',
        'Vaca atolada',
        'Yakult',
        'Yentafo',
        'Zabaione',
        'Zucchini',
        'Abacaxi',
        'Abobrinha recheada',
        'Aspargos grelhados',
        'Baião de dois com carne seca',
        'Canelone de queijo',
        'Carne de panela',
        'Feijoada',
        'Pão de alho',
        'Risoto de cogumelos'
    ]
    let imprimir = document.getElementById('comida')

    imprimir.innerHTML = ''
    for(let i = 0; i < comidas.length; i++) {
        imprimir.innerHTML += `<option value='${comidas[i]}'>${comidas[i]}</option>`
    }
})